### ISSUE TITLE
ios and eos parser parsing interface error in special case

### ISSUE THREAD

**Issue by yapengwu** [napalm-automation/napalm-yang#158]
When I parsing the following configuration for interface model, I hit error:

```
interface Loopback101
 description loopback for vrf green
 vrf forwarding green
 ip address 172.16.0.1 255.255.255.255
!
```
```
  File "/home/xxx/virtenvs/napalm-yang/local/lib/python2.7/site-packages/napalm_yang-0.1.0-py2.7.egg/napalm_yang/parsers/jsonp.py", line 118, in _parse_leaf_default
    d = mapping["map"][d.lower()]
KeyError: u'loopback10'
```
It is due to the "regexp" match rule:
```
        config:
            _process: unnecessary
            name:
                _process: unnecessary
            type:
                _process:
                    - pre: "{{ interface_key }}"
                      regexp: "(?P<value>(\\w|-)*)\\d+"
                      map:
                          fastethernet: ethernetCsmacd
                          gigabitethernet: ethernetCsmacd
                          management: ethernetCsmacd
                          loopback: softwareLoopback
                          port-channel: ieee8023adLag
                          vlan: l3ipvlan
```
