### ISSUE TITLE
Unable to parse model with attribute "max"

### ISSUE THREAD

**Issue by bewing** [napalm-automation/napalm-yang#36]
When attempting to parse openconfig-platform via parse_state(), an error is thrown when processing the "max" key:

```python
Finding parser for openconfig-platform:components
Found on profile: eos, /home/bewing/napalm-yang/napalm_yang/mappings/eos/parsers/state/openconfig-platform/components.yaml
Parsing attribute: /components
Parsing attribute: /components/component
Parsing attribute: /components/component
Parsing element component[xcvrSlots_52]
Parsing attribute: /components/component[name='xcvrSlots_52']
Parsing attribute: /components/component[name='xcvrSlots_52']/name
Parsing attribute: /components/component[name='xcvrSlots_52']/subcomponents
Parsing attribute: /components/component[name='xcvrSlots_52']/subcomponents
Parsing attribute: /components/component[name='xcvrSlots_52']/subcomponents/subcomponent
Parsing attribute: /components/component[name='xcvrSlots_52']/subcomponents/subcomponent
Parsing attribute: /components/component[name='xcvrSlots_52']/transceiver
Skipping attribute: openconfig-platform-transceiver:xcvrSlots_52
Finding parser for openconfig-platform-transceiver:transceiver
Couldn't find parsing file: /home/bewing/napalm-yang/napalm_yang/mappings/eos/parsers/state/openconfig-platform-transceiver/transceiver.yaml
Parsing attribute: /components/component[name='xcvrSlots_52']/state
Parsing attribute: /components/component[name='xcvrSlots_52']/state
Parsing attribute: /components/component[name='xcvrSlots_52']/state/version
Parsing attribute: /components/component[name='xcvrSlots_52']/state/version
Parsing attribute: /components/component[name='xcvrSlots_52']/state/name
Parsing attribute: /components/component[name='xcvrSlots_52']/state/name
Parsing attribute: /components/component[name='xcvrSlots_52']/state/temperature
Parsing attribute: /components/component[name='xcvrSlots_52']/state/temperature
Parsing attribute: /components/component[name='xcvrSlots_52']/state/temperature/avg
Parsing attribute: /components/component[name='xcvrSlots_52']/state/temperature/avg
Parsing attribute: /components/component[name='xcvrSlots_52']/state/temperature/instant
Parsing attribute: /components/component[name='xcvrSlots_52']/state/temperature/instant
Parsing attribute: /components/component[name='xcvrSlots_52']/state/temperature/max
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    config.parse_state(d, profile=['eos'])
  File "/home/bewing/napalm-yang/napalm_yang/base.py", line 251, in parse_state
    parser.parse()
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 73, in parse
    self._parse(self._yang_name, self.model, self.mapping[self._yang_name])
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 79, in _parse
    self._parse_container(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 102, in _parse_container
    self._parse(k, v, mapping[k])
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 81, in _parse
    self._parse_list(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 133, in _parse_list
    self._parse(key, obj, element_mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 79, in _parse
    self._parse_container(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 102, in _parse_container
    self._parse(k, v, mapping[k])
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 79, in _parse
    self._parse_container(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 102, in _parse_container
    self._parse(k, v, mapping[k])
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 79, in _parse
    self._parse_container(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 102, in _parse_container
    self._parse(k, v, mapping[k])
KeyError: 'max_'
```

**Comment by bewing** [comment]
The YAML profile we were using:
```yaml
---
metadata:
    parser: DictParser
    execute:
        - method: "device.run_commands"
          args:
              commands: ["show inventory"]

components:
    _parse: unnecessary
    component:
        _parse:
            mode: dict
            from: "{%- set data = {} -%}{%- for k, v in bookmarks.components.0.0.items() -%}{%- if v is mapping and k is not equalto 'systemInformation' -%}{%- for kk, vv in v.items() -%}{%- do data.update({'{}_{}'.format(k,kk): vv}) -%} {%- endfor -%} {%- endif -%} {%- endfor -%} {{ data|json }}"
        name:
            _parse: unnecessary
        config:
            _parse: unnecessary
        state:
            _parse: unnecessary
            name:
                _parse: not_implemented
            type:
                _parse: not_implemented
            id:
                _parse: not_implemented
            description:
                _parse: not_implemented
            mfg-name:
                _parse: not_implemented
            version:
                _parse: not_implemented
            serial-no:
                _parse: not_implemented
            part-no:
                _parse: not_implemented
            temperature:
                _parse: unnecessary
                instant:
                    _parse: not_implemented
                avg:
                    _parse: not_implemented
                min:
                    _parse: not_implemented
                max:
                    _parse: not_implemented
            properties:
                _parse: unnecessary
                property:
                    _parse: not_implemented
                    name:
                    config:
                        name:
                        value:
                    state:
                        name:
                        value:
                        configurable:
        subcomponents:
            _parse: unnecessary
            subcomponent:
                _parse: not_implemented
                name:
                config:
                    name:
                state:
                name:
```
