### ISSUE TITLE
Discussion: Complex models (oc-platform)

### ISSUE THREAD

**Issue by bewing** [napalm-automation/napalm-yang#39]
While working on #38 and the openconfig-platform YANG model, I ran into significant difficulties attempting to use the yaml-configured parsers to transform the data models from the devices to the YANG data model.  While this may only come into play in extremely complex models, is there a desire to have a standardized way to handle this?

Do we want to propose more base methods designed to return OC-standard dicts, and use load_dict()?

Start adding private, non-base methods to drivers to do the same?

Create a "python" parser that will take the output of the commands and run a method defined in napalm_yang.helpers?

I did write up a procedural method to process EOS inventory, temperature, and transceiver data into a pretty complete model: https://gist.github.com/bewing/3c1a35781cbc6bef4dd88f6f60f69b01

**Comment by dbarrosop** [comment]
Would you do me a favor and provide the raw data as well? That way I can write a test and try to make it pass with the framework :)

**Comment by bewing** [comment]
gist updated

**Comment by bewing** [comment]
Maybe this is all non-starting -- cProfile of load_dict() of a fully populated chassis into the platform model:
`         17124891 function calls (14179173 primitive calls) in 22.662 seconds`

A ToR switch takes ~5 seconds, though.

**Comment by dbarrosop** [comment]
how much of that time is just waiting for `d.device.run_commands` to return?

I see two options:

1. We assume calling this is something people does once a week and we don't care about speed. I don't think it will be this bad for other models.
2. We start thinking in ways to filter the model. For example something like `parse_state(filter="components.component[name].type== LINECARD")`.

**Comment by bewing** [comment]
> how much of that time is just waiting for `d.device.run_commands` to return?

I actually profiled JUST the dict_load:

    `cProfile.run('config.load_dict(eos_oc_platform(inv,temp, ints["interfaces"], trans["interfaces"]))')`

The full profile output is here: https://gist.github.com/bewing/3d0916918ce69ce97b20d009ebbcff90

> We assume calling this is something people does once a week and we don't care about speed. I don't think it will be this bad for other models.

Unfortunately, some of this data (environment, transceiver) may be accessed more often.

Thinking about it, the only real point of parsing the state wtih load_dict is to validate the data against the model itself -- you're basically getting back out with config.get() that you're putting in with the dictionary.

**Comment by dbarrosop** [comment]
Other methods might want to use `load_dict` as post maintenance check, ie, gather state before maintenance, save it in JSON file, perform maintenance, gather state from live network, load_dict from previous JSON file, diff them. But this is not the case here.

So, two things:

1. Regarding performance, not sure if we can do anything. `load_dict` is called 3764 times due to the amount of data being parsed... We can add filters as suggested previously but that's going to be tricky (it's a feature we will need eventually I think anyway but I wanted to see first how people was using this library before making up my mind).
2. Regarding complex models, I think this is something very complex that will require some thought. My suggestion short term is as follows:
   1. Create a method that returns the data you want already formatted (pretty much what's done in the gist).
   2. Create a profile that calls that method and uses the `JSONParser` to map gathered data by the method and the model.
   3. Profile it and check if there is a significant drop in performance compare to bare `load_dict`.

I still want to use the parser if possible as we can use that as documentation and testing.

In the meantime, I'd look how to best do this without requiring extra code but that might take time or be so hard and so niche that this solution might be best (I still think this is the only model that is going to be this complex).

Thoughts?

**Comment by bewing** [comment]
So I rewrote this to use the JSON parser from #38, and a new profile that looked like this:
```yaml
---
metadata:
    processor: JSONParser

components:
    _process: unnecessary
    component:
        _process:
            mode: dict
            from: "{{ bookmarks.components.0.components.component|json }}"
        config:
            _process: not_implemented
            name:
                _process: not_implemented
        name:
            _process: not_implemented
        properties:
            _process: unnecessary
            property:
                _process:
                    mode: dict
                    from: "{{ bookmarks.parent.get('properties', {}).get('property', {})|json }}"
                config:
                    _process: not_implemented
                    name:
                        _process: not_implemented
                    value:
                        _process: not_implemented
                name:
                    _process: not_implemented
                state:
                    _process: unnecessary
                    configurable:
                        _process: not_implemented
                    name:
                        _process:
                            mode: value
                            value: "{{ parent_key }}"
                    value:
                        _process:
                            mode: value
                            value: "{{ bookmarks.parent.state.value }}"
```
etc etc etc
The profiles for using the JSON parser, and load_dict are here:  https://gist.github.com/bewing/9870117d1f135fdd390bc63c32b15573

We may just have to live with the performance of load_dict for the more complex models.
