### ISSUE TITLE
translate_config merge for containers with _process: unnecesary

### ISSUE THREAD

**Issue by matejv** [napalm-automation/napalm-yang#66]
Let's consider the EOS translations for static-routes in develop branch.

Also running config has a static route:

```python
running = napalm_yang.base.Root()
running.add_model(napalm_yang.models.openconfig_network_instance)
running.load_dict({'network_instances': {'network_instance': {u'global': {'config': {'enabled': True,
     'type': u'DEFAULT_INSTANCE'},
    'name': u'global',
    'protocols': {'protocol': {u'static static': {'identifier': u'static',
       'name': u'static',
       'static_routes': {'static': {u'2.2.2.2/32': {'config': {'prefix': u'2.2.2.2/32'},
          'next_hops': {'next_hop': {u'10.1.1.9': {'config': {'next_hop': u'10.1.1.9'},
             'index': u'10.1.1.9'}}},
          'prefix': u'2.2.2.2/32'}}}}}}}}}}
)
```

And candidate config has a different static route:

```python
candidate = napalm_yang.base.Root()
candidate.add_model(napalm_yang.models.openconfig_network_instance)
candidate.load_dict({'network_instances': {'network_instance': {u'global': {'config': {'enabled': True,
     'type': u'DEFAULT_INSTANCE'},
    'name': u'global',
    'protocols': {'protocol': {u'static static': {'identifier': u'static',
       'name': u'static',
       'static_routes': {'static': {u'3.3.3.3/32': {'config': {'prefix': u'3.3.3.3/32'},
          'next_hops': {'next_hop': {u'10.1.1.9': {'config': {'next_hop': u'10.1.1.9'},
             'index': u'10.1.1.9'}}},
          'prefix': u'3.3.3.3/32'}}}}}}}}}}
)
```

And we want to merge candidate into running:

```python
configuration = candidate.translate_config(profile=[profile], merge=running)
```

The new route gets added, but the old one didn't get removed:

```
>>> print configuration
ip route 3.3.3.3/32 10.1.1.9
```

Same issue with replace:

```python
>>> configuration = candidate.translate_config(profile=[profile], replace=running)
>>> print configuration
no ip route 3.3.3.3/32 10.1.1.9
ip route 3.3.3.3/32 10.1.1.9
```

With logging turned on you see this:

```
INFO:napalm-yang:Defaulting static: 2.2.2.2/32
```

But the translator for EOS has this:
```yaml
static:
    _process: unnecessary
```

So nothing happens. All the action is hidden under `next-hop`, but the framework doesn't descend that far - which is fine.

Ideally we could modify the mappings to something like this:

```yaml
...
static:
    _process:
      - mode: container
        key_value: "ip route {{ static_key }}"
        negate: "no ip route {{ static_key }}\n"
        end: "\n"
    next-hops:
        _process: unnecessary
        next-hop:
            _process:
              - mode: container
                key_value: " {{ next_hop_key }}"
                negate: " {{ next_hop_key }}\n"
...
```

This looks nice and more maintainable than the current approach. But that doesn't work for static routes with multiple next-hops, you'll get this:

```
ip route 3.3.3.3/32 10.1.1.9 10.1.1.2
```

instead of

```
ip route 3.3.3.3/32 10.1.1.9
ip route 3.3.3.3/32 10.1.1.2
```

---

My suggestion is to add another attribute to `mode: container` that would repeat `key_value` for each child. Kind of the opposite of `flat: true` in text parser. Something like:

```yaml
...
static:
    _process:
      - mode: container
        key_value: "ip route {{ static_key }}"
        negate: "no ip route {{ static_key }}\n"
        repeat_for_children: true
        end: "\n"
    next-hops:
        _process: unnecessary
        next-hop:
            _process:
              - mode: container
                key_value: " {{ next_hop_key }}"
                negate: " {{ next_hop_key }}\n"
...
```

What do you think?

(wanted to make a POC but I'm still struggling with the internal logic of translators/parsers)

**Comment by dbarrosop** [comment]
> static:
>    _process: unnecessary
> So nothing happens. All the action is hidden under next-hop, but the framework doesn't descend > that far - which is fine.

`unnecessary` doesn't stop the execution. Note that most parsers start with that action:

https://github.com/napalm-automation/napalm-yang/blob/develop/napalm_yang/mappings/eos/parsers/config/openconfig-interfaces/interfaces.yaml#L9

`not_implemented` and `unsupported` will actually stop traversing the tree. For example:

https://github.com/napalm-automation/napalm-yang/blob/develop/napalm_yang/mappings/eos/parsers/config/openconfig-network-instance/network-instances.yaml#L54

In any case, I think what you are suggesting is a good idea. Might implement in this way though:

```
static:
    _process:
      - mode: oneliner
        prefix: "ip route {{ static_key }}"
        negate: "no ip route {{ static_key }}\n"
        negate_prefix: "no ip route {{ static_key }}"
    next-hops:
        _process: unnecessary
        next-hop:
            _process:
              - mode: container
                key_value: "{{ prefix }} {{ next_hop_key }}"
                negate: "{{ negate_prefix}} {{ next_hop_key }}\n"
```

Or something like that.

**Comment by matejv** [comment]
So if I understand correctly:

* `oneliner` by itself would normally not output anything
* descendants of `oneliner` can use `prefix` and `negate_prefix` in their attributes
* if a `oneliner` needs to be negated (defaulted) the `negate` attribute is used and execution of that branch stops

I might even be able to implement this myself. Let me see if I can it.

**Comment by dbarrosop** [comment]
I have been thinking a bit more about this and although around the same lines we could do this instead:

```
    _process:
      - mode: container
        prefix: "ip route {{ static_key }}"
        negate: "no ip route {{ static_key }}\n"
        negate_prefix: "no ip route {{ static_key }}"
```

I don't think we need a one-liner as I think this `prefix` could be generalized. In any case, a container with a `prefix` and a `negate_prefix` should populate `extra_vars.prefix` and `extra_vars.negate_prefix`. The idea of reusing the container is that this should be easy to add and might allow to prepend a `prefix` even if you need to add a command here (for example, you will probably need to do that when processing next-hops as you might want to create the next-hop but later on you might want to append the metric or a tag or something else). The reason why I am proposing to reuse `extra_vars` for this it's because it's probably quite straightforward to do so but feel free to look into adding the variables directly if you prefer.
